### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by OxNinja**

### CODE REVIEW

**Comment by isf3t** [comment]
gigem{y0u_4r3_n07_funny} 🚀

**Comment by zeredy879** [comment]
gigem{Im_tru3_f10g!!}

**Comment by lhhaber** [comment]
🧐

**Comment by TacEx-053** [comment]
🧐

**Comment by addisoncrump** [comment]
Closing because you're literally trolling LMAO

Competitors: this is not a valid path.

**Pull request closed without merging**
